### ISSUE TITLE
TMM count hardcoded

### ISSUE THREAD

**Issue by emalzer** [elk-f5ddos/DDOS-Dashboard#1]
Hi!

It's not really ideal that the TMM count is hardcoded within the Logstash configuration.
As far as I saw this is only used for the statistics calculations and the statistics output is exported from the tmctl command.

The command can be modified to include the TMM count at the end of the tmctl output like this:

```tmctl -c dos_stat -s context_name,vector_name,attack_detected,stats_rate,drops_rate,int_drops_rate,ba_stats_rate,ba_drops_rate,bd_stats_rate,bd_drops_rate,detection,mitigation_low,mitigation_high,detection_ba,mitigation_ba_low,mitigation_ba_high,detection_bd,mitigation_bd_low,mitigation_bd_high | grep -v "context_name" | sed 's/$/,'"`tmsh show sys tmm-info |grep 'Sys::TMM' | wc -l`"'/' | logger -n 1.1.1.1 --udp --port 5556```

This adds a number with the current TMM count.

Greetings,
Eric

**Comment by shaath1** [comment]
Thanks for the suggestion eric will test this and update the logstash.conf

**Comment by sv3n-mu3ll3r** [comment]
Hi Eric,
you are fully right and we changed it. Will be available with the next update. 
Thanks, sVen
