### ISSUE TITLE
How to send DOS_stats if destination is a local VS?

### ISSUE THREAD

**Issue by emalzer** [elk-f5ddos/DDOS-Dashboard#2]
Hi,

I have the situation that the logging cluster gets loadbalanced through the very same BIG-IP which is exporting the data.
If I use the crontab method I can use the VS IP as destination. The approach with an external monitor is great, but does not work if the destination is a local virtual server :( Any other idea?

Greetings,
Eric

**Comment by shaath1** [comment]
@sv3n-mu3ll3r

**Comment by sv3n-mu3ll3r** [comment]
Eric, 
I will look into it. 
Thanks for the info. Cheers, sVen

**Comment by shaath1** [comment]
solved

**Comment by emalzer** [comment]
> solved

@shaath1 how?
